--==============================================================================
-- SCRIPT DE BASE DE DATOS (VERSIÓN POA POR UNIDAD)
-- Proyecto: Seguimiento de Metas POA Institucional
-- Versión: 2.0
-- Descripción: Modelo de datos ajustado para gestionar metas por Unidad
-- Administrativa, incluyendo campos específicos para indicadores POA.
--==============================================================================

--==============================================================================
-- 0. ELIMINACIÓN DE OBJETOS EXISTENTES (para re-ejecución)
--==============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE poa_historial_avances';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE poa_metas';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/


--==============================================================================
-- 1. TABLAS
--==============================================================================

-- Tabla principal de metas del POA, vinculada a la Unidad Administrativa
CREATE TABLE poa_metas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- --- Datos del Indicador/Meta ---
    nombre_indicador VARCHAR2(300) NOT NULL,
    formula VARCHAR2(500),
    linea_base VARCHAR2(100) DEFAULT '0',
    meta_valor NUMBER NOT NULL, -- Renombrado de 'valor_meta' para claridad
    unidad_medida VARCHAR2(100),
    fecha_meta DATE, -- Renombrado de 'fecha_fin'
    rango_tolerancia VARCHAR2(50), -- Ej: "30%", "±5"
    periodicidad VARCHAR2(50)
        CHECK (periodicidad IN ('MENSUAL', 'BIMESTRAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL')),

    -- --- Unidad Responsable de la Meta ---
    id_unidad_responsable NUMBER(9,0) NOT NULL REFERENCES SYS_UNIDAD_ADMINISTRATIVA(ID_UNIDAD_ADMINISTRATIVA),

    -- --- Campos de Seguimiento ---
    progreso_actual NUMBER DEFAULT 0,
    estado VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'EN PROGRESO', 'CUMPLIDO', 'EN RIESGO', 'INCUMPLIDO')),

    -- --- Campos de Auditoría ---
    usuario_creador VARCHAR2(100),
    fecha_creacion DATE DEFAULT SYSDATE
);

-- Tabla para registrar los avances periódicos de cada meta
CREATE TABLE poa_historial_avances (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    meta_id NUMBER REFERENCES poa_metas(id) ON DELETE CASCADE,
    fecha_registro DATE DEFAULT SYSDATE,
    usuario_registro VARCHAR2(100), -- Puede ser el ID_FUNCIONARIO o el USERNAME
    valor_anterior NUMBER,
    valor_nuevo NUMBER,
    observaciones CLOB,
    documento_adjunto BLOB -- Opcional: para adjuntar evidencia
);


--==============================================================================
-- 2. TRIGGERS
--==============================================================================

-- Trigger que actualiza el progreso y estado de la meta al registrar un avance
CREATE OR REPLACE TRIGGER trg_actualizar_progreso_poa_v2
AFTER INSERT ON poa_historial_avances
FOR EACH ROW
DECLARE
    v_meta poa_metas%ROWTYPE;
BEGIN
    -- Obtener datos de la meta para calcular el estado
    SELECT * INTO v_meta FROM poa_metas WHERE id = :NEW.meta_id;

    -- Actualizar la tabla principal de metas
    UPDATE poa_metas
    SET
        progreso_actual = :NEW.valor_nuevo,
        estado =
            CASE
                -- Si el nuevo valor alcanza o supera la meta, está CUMPLIDO
                WHEN :NEW.valor_nuevo >= meta_valor THEN 'CUMPLIDO'
                -- Si la fecha de la meta ya pasó y no se ha cumplido, está INCUMPLIDO
                WHEN fecha_meta < SYSDATE THEN 'INCUMPLIDO'
                -- Si no, sigue EN PROGRESO (se puede añadir lógica para "EN RIESGO" aquí)
                ELSE 'EN PROGRESO'
            END
    WHERE id = :NEW.meta_id;
END;
/

--==============================================================================
-- 3. VISTAS
--==============================================================================

-- Vista que enriquece los datos de la meta con la información de la Unidad
CREATE OR REPLACE VIEW V_POA_METAS_UNIDAD AS
SELECT
    m.id,
    m.nombre_indicador,
    m.formula,
    m.linea_base,
    m.meta_valor,
    m.unidad_medida,
    m.fecha_meta,
    m.rango_tolerancia,
    m.periodicidad,
    m.id_unidad_responsable,
    ua.titulo AS unidad_responsable_nombre,
    ua.sigla AS unidad_responsable_sigla,
    ua.cua_padre,
    m.progreso_actual,
    m.estado,
    m.usuario_creador,
    m.fecha_creacion,
    -- Cálculo del porcentaje de cumplimiento para visualización
    CASE
        WHEN m.meta_valor > 0 THEN
            ROUND((m.progreso_actual / m.meta_valor) * 100, 2)
        ELSE 0
    END AS porcentaje_cumplimiento
FROM
    poa_metas m
JOIN
    SYS_UNIDAD_ADMINISTRATIVA ua ON m.id_unidad_responsable = ua.id_unidad_administrativa;
