--==============================================================================
-- SCRIPT DE BASE DE DATOS (VERSIÓN SIMPLIFICADA)
-- Proyecto: Mi POA Individual
-- Versión: 1.0
-- Descripción: Modelo de datos mínimo para que un funcionario pueda
-- registrar sus metas del POA y sus avances periódicos.
--==============================================================================

--==============================================================================
-- 0. ELIMINACIÓN DE OBJETOS EXISTENTES (para re-ejecución)
--==============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE poa_historial_avances';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE poa_metas';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/


--==============================================================================
-- 1. TABLAS
--==============================================================================

-- Tabla principal de metas del POA
CREATE TABLE poa_metas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(250) NOT NULL,
    descripcion CLOB,

    -- --- Vinculación con el funcionario dueño de la meta ---
    id_funcionario NUMBER(9,0) NOT NULL REFERENCES SYS_FUNCIONARIO(ID_FUNCIONARIO),

    -- Fechas y plazos
    fecha_creacion DATE DEFAULT SYSDATE,
    fecha_inicio DATE,
    fecha_fin DATE,

    -- Valores para medir el progreso
    valor_inicial NUMBER DEFAULT 0,
    valor_meta NUMBER,
    unidad_medida VARCHAR2(100), -- Ej: "Informes", "Capacitaciones", "%", etc.
    progreso_actual NUMBER DEFAULT 0,

    -- Cálculos automáticos para estado y porcentaje
    porcentaje_completado NUMBER GENERATED ALWAYS AS (
        CASE
            WHEN valor_meta > valor_inicial THEN
                ROUND(((progreso_actual - valor_inicial) / (valor_meta - valor_inicial)) * 100, 2)
            WHEN valor_meta <= valor_inicial AND progreso_actual >= valor_meta THEN 100
            ELSE 0
        END
    ) VIRTUAL,

    estado VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'EN PROGRESO', 'COMPLETADO', 'ATRASADO', 'CANCELADO'))
);

-- Tabla para registrar los avances de cada meta
CREATE TABLE poa_historial_avances (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    meta_id NUMBER REFERENCES poa_metas(id) ON DELETE CASCADE,
    fecha_registro DATE DEFAULT SYSDATE,
    usuario_registro NUMBER(9,0) REFERENCES SYS_FUNCIONARIO(ID_FUNCIONARIO),
    valor_anterior NUMBER,
    valor_nuevo NUMBER,
    observaciones CLOB
);


--==============================================================================
-- 2. TRIGGERS
--==============================================================================

-- Trigger que se dispara al insertar un nuevo avance en el historial.
-- Actualiza el progreso y el estado de la meta principal.
CREATE OR REPLACE TRIGGER trg_actualizar_progreso_poa
AFTER INSERT ON poa_historial_avances
FOR EACH ROW
DECLARE
    v_fecha_fin DATE;
BEGIN
    -- Obtener la fecha de fin de la meta para el cálculo del estado
    SELECT fecha_fin INTO v_fecha_fin FROM poa_metas WHERE id = :NEW.meta_id;

    -- Actualizar la tabla principal de metas
    UPDATE poa_metas
    SET
        progreso_actual = :NEW.valor_nuevo,
        estado =
            CASE
                -- Si el nuevo valor alcanza o supera la meta, se marca como COMPLETADO
                WHEN :NEW.valor_nuevo >= valor_meta THEN 'COMPLETADO'
                -- Si la fecha de fin ya pasó y no se ha completado, está ATRASADO
                WHEN v_fecha_fin < SYSDATE THEN 'ATRASADO'
                -- Si hay algún progreso y no está completada ni atrasada, está EN PROGRESO
                WHEN :NEW.valor_nuevo > valor_inicial THEN 'EN PROGRESO'
                -- Si no, sigue PENDIENTE
                ELSE 'PENDIENTE'
            END
    WHERE id = :NEW.meta_id;
END;
/


--==============================================================================
-- 3. VISTAS (Opcional, pero recomendado para simplificar APEX)
--==============================================================================

-- Vista que une la meta con los datos del funcionario para mostrar su nombre.
CREATE OR REPLACE VIEW V_POA_METAS_FUNCIONARIO AS
SELECT
    m.id,
    m.nombre,
    m.descripcion,
    m.id_funcionario,
    f.nombre || ' ' || f.apellido AS funcionario_nombre,
    m.fecha_creacion,
    m.fecha_inicio,
    m.fecha_fin,
    m.valor_inicial,
    m.valor_meta,
    m.unidad_medida,
    m.progreso_actual,
    m.porcentaje_completado,
    m.estado
FROM
    poa_metas m
JOIN
    SYS_FUNCIONARIO f ON m.id_funcionario = f.id_funcionario;
