--==============================================================================
-- SCRIPT DE BASE DE DATOS PARA EL TABLERO DE SEGUIMIENTO DE METAS
-- Versión: 2.1
-- Descripción: Script re-ejecutable. Elimina objetos existentes antes de
-- crearlos para evitar errores ORA-00955. También limpia datos
-- de ejemplo antes de insertarlos para prevenir errores ORA-00001.
--==============================================================================

--==============================================================================
-- 0. ELIMINACIÓN DE OBJETOS EXISTENTES (para re-ejecución)
--==============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_METAS_DETALLE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE historial_avances';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE hitos_metas';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE metas';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE categorias_metas';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 AND SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

--==============================================================================
-- 1. TABLAS
--==============================================================================

-- Tabla de categorías (Maestro para clasificar metas)
CREATE TABLE categorias_metas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    descripcion VARCHAR2(500),
    color VARCHAR2(20),
    icono VARCHAR2(100)
);

-- Tabla principal de metas (Corazón del sistema)
-- Se integra con SYS_UNIDAD_ADMINISTRATIVA y SYS_FUNCIONARIO
CREATE TABLE metas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200) NOT NULL,
    descripcion CLOB,
    tipo_meta VARCHAR2(50) DEFAULT 'CUANTITATIVA'
        CHECK (tipo_meta IN ('CUANTITATIVA', 'CUALITATIVA')),

    -- --- LLAVES FORÁNEAS A TABLAS EXISTENTES ---
    departamento_id NUMBER(9,0) REFERENCES SYS_UNIDAD_ADMINISTRATIVA(ID_UNIDAD_ADMINISTRATIVA),
    usuario_responsable NUMBER(9,0) REFERENCES SYS_FUNCIONARIO(ID_FUNCIONARIO),
    usuario_creador NUMBER(9,0) REFERENCES SYS_FUNCIONARIO(ID_FUNCIONARIO),
    -- -----------------------------------------

    categoria_id NUMBER REFERENCES categorias_metas(id),

    -- Fechas y plazos
    fecha_creacion DATE DEFAULT SYSDATE,
    fecha_inicio DATE,
    fecha_fin DATE,
    fecha_cierre DATE,

    -- Valores y progreso
    valor_meta NUMBER,
    valor_inicial NUMBER DEFAULT 0,
    unidad_medida VARCHAR2(50),
    progreso_actual NUMBER DEFAULT 0,

    -- Columna virtual para el cálculo automático del porcentaje
    porcentaje_completado NUMBER GENERATED ALWAYS AS (
        CASE
            WHEN valor_meta > valor_inicial THEN
                ROUND(((progreso_actual - valor_inicial) / (valor_meta - valor_inicial)) * 100, 2)
            WHEN valor_meta <= valor_inicial AND progreso_actual >= valor_meta THEN 100
            ELSE 0
        END
    ) VIRTUAL,

    -- Estado y prioridad con restricciones CHECK para consistencia de datos
    estado VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'EN PROGRESO', 'COMPLETADO', 'ATRASADO', 'CANCELADO')),
    prioridad VARCHAR2(20) DEFAULT 'MEDIA'
        CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    complejidad VARCHAR2(20)
        CHECK (complejidad IN ('BAJA', 'MEDIA', 'ALTA')),

    -- Metadatos
    indicadores_clave VARCHAR2(500),
    presupuesto_asignado NUMBER,
    presupuesto_utilizado NUMBER DEFAULT 0
);

-- Tabla de hitos/intermediarios (Sub-tareas o checkpoints de una meta)
CREATE TABLE hitos_metas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    meta_id NUMBER REFERENCES metas(id) ON DELETE CASCADE, -- Se borra en cascada si se elimina la meta
    nombre VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(500),
    fecha_objetivo DATE,
    fecha_completado DATE,
    valor_objetivo NUMBER,
    completado VARCHAR2(1) DEFAULT 'N' CHECK (completado IN ('S', 'N'))
);

-- Tabla de registro de avances (Historial de cambios de progreso)
CREATE TABLE historial_avances (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    meta_id NUMBER REFERENCES metas(id) ON DELETE CASCADE, -- Se borra en cascada
    fecha_registro DATE DEFAULT SYSDATE,
    usuario_registro NUMBER(9,0) REFERENCES SYS_FUNCIONARIO(ID_FUNCIONARIO), -- Quién registra el avance
    valor_anterior NUMBER,
    valor_nuevo NUMBER,
    diferencia NUMBER GENERATED ALWAYS AS (valor_nuevo - valor_anterior) VIRTUAL, -- Columna calculada
    observaciones CLOB
);

--==============================================================================
-- 2. TRIGGERS
--==============================================================================

-- Trigger para actualizar el progreso de la meta principal al registrar un avance
-- y asignar el estado correcto (EN PROGRESO, COMPLETADO, ATRASADO).
CREATE OR REPLACE TRIGGER trg_actualizar_progreso_meta
AFTER INSERT ON historial_avances
FOR EACH ROW
BEGIN
    UPDATE metas
    SET
        progreso_actual = :NEW.valor_nuevo,
        estado =
            CASE
                -- Si el nuevo valor alcanza o supera la meta, se completa
                WHEN :NEW.valor_nuevo >= valor_meta THEN 'COMPLETADO'
                -- Si la fecha de fin ya pasó y no está completa, está atrasada
                WHEN fecha_fin < SYSDATE THEN 'ATRASADO'
                -- De lo contrario, está en progreso
                ELSE 'EN PROGRESO'
            END,
        -- Si se completa, se sella la fecha de cierre
        fecha_cierre =
            CASE
                WHEN :NEW.valor_nuevo >= valor_meta THEN SYSDATE
                ELSE fecha_cierre
            END
    WHERE id = :NEW.meta_id;
END;
/

-- Trigger para gestionar el estado de una meta si se modifica directamente,
-- por ejemplo, al cambiar la fecha de fin.
CREATE OR REPLACE TRIGGER trg_gestionar_estado_meta
BEFORE UPDATE ON metas
FOR EACH ROW
BEGIN
    -- No permitir cambiar estado si ya está cancelado o completado (a menos que se reabra)
    IF :OLD.estado IN ('COMPLETADO', 'CANCELADO') AND :NEW.estado = :OLD.estado THEN
        :NEW.estado := :OLD.estado; -- Mantiene el estado
    -- Si la fecha de fin se mueve al pasado y no está completada, marcar como ATRASADO
    ELSIF :NEW.fecha_fin < SYSDATE AND :NEW.porcentaje_completado < 100 THEN
        :NEW.estado := 'ATRASADO';
    -- Si el progreso es mayor a 0 y menor a 100, y no está atrasada, es EN PROGRESO
    ELSIF :NEW.progreso_actual > :NEW.valor_inicial AND :NEW.porcentaje_completado < 100 THEN
        :NEW.estado := 'EN PROGRESO';
    END IF;
END;
/


--==============================================================================
-- 3. VISTAS (Views para simplificar las consultas en APEX)
--==============================================================================

-- Vista que une la meta con sus tablas maestras para facilitar la creación de reportes.
CREATE OR REPLACE VIEW V_METAS_DETALLE AS
SELECT
    m.id,
    m.nombre,
    m.descripcion,
    m.tipo_meta,
    m.categoria_id,
    c.nombre AS categoria_nombre,
    c.color AS categoria_color,
    c.icono AS categoria_icono,
    m.departamento_id,
    ua.titulo AS departamento_nombre,
    m.usuario_responsable,
    resp.nombre || ' ' || resp.apellido AS responsable_nombre,
    m.usuario_creador,
    crea.nombre || ' ' || crea.apellido AS creador_nombre,
    m.fecha_creacion,
    m.fecha_inicio,
    m.fecha_fin,
    m.fecha_cierre,
    m.valor_meta,
    m.valor_inicial,
    m.unidad_medida,
    m.progreso_actual,
    m.porcentaje_completado,
    m.estado,
    m.prioridad,
    m.complejidad,
    m.indicadores_clave,
    m.presupuesto_asignado,
    m.presupuesto_utilizado,
    (m.fecha_fin - m.fecha_inicio) AS duracion_dias,
    CASE
        WHEN m.estado NOT IN ('COMPLETADO', 'CANCELADO') AND m.fecha_fin < SYSDATE
        THEN 'SI'
        ELSE 'NO'
    END AS esta_atrasada
FROM
    metas m
LEFT JOIN
    categorias_metas c ON m.categoria_id = c.id
LEFT JOIN
    SYS_UNIDAD_ADMINISTRATIVA ua ON m.departamento_id = ua.id_unidad_administrativa
LEFT JOIN
    SYS_FUNCIONARIO resp ON m.usuario_responsable = resp.id_funcionario
LEFT JOIN
    SYS_FUNCIONARIO crea ON m.usuario_creador = crea.id_funcionario;

--==============================================================================
-- INSERTS INICIALES (Datos de ejemplo)
--==============================================================================
-- Se limpia la tabla antes de insertar para evitar errores de duplicados
DELETE FROM categorias_metas;

INSERT INTO categorias_metas (nombre, color, icono) VALUES ('Estratégica', '#007bff', 'fa-chess-king');
INSERT INTO categorias_metas (nombre, color, icono) VALUES ('Operativa', '#28a745', 'fa-cogs');
INSERT INTO categorias_metas (nombre, color, icono) VALUES ('Financiera', '#ffc107', 'fa-dollar-sign');
COMMIT;
